import { NFTPORT_API_KEY } from '@src/helpers';

/**
 * Uses the NFTPort API to fetch the Assets generated by the current account.
 */
const fetchAssets = (addr) => {
  if (typeof addr !== 'undefined') {
    console.log(addr);
    console.log(typeof addr);
    const url = `https://api.nftport.xyz/v0/accounts/${addr}?chain=polygon&account_address=${addr}&continuation=&include=metadata`;
    return new Promise((resolve, reject) => {
      fetch(url, {
        method: 'GET',
        headers: {
          'Content-Type': 'json',
          Authorization: NFTPORT_API_KEY,
        },
      })
        .then((res) => res.json())
        .then((json) => {
          resolve(json);
        })
        .catch((err) => reject(err));
    });
  } else {
    return new Promise((resolve, reject) =>
      reject('Address undefined.  Connect Wallet to continue'),
    );
  }
};

export default fetchAssets;
